test
Steffb98/Banking-Application pull request #1
Opened 2020-11-21 15:20 UTC by Steffb98

2020-11-21 15:20 UTC, Steffb98 commented
Hoi mensen

2020-11-22 13:15 UTC, moochoo112 commented
hallo

2020-11-22 13:15 UTC, Zalmwel commented
Erg fraai dit steff!

2020-11-22 13:17 UTC, Zalmwel requested changes
Wil je het naar personen veranderen?

2020-11-22 13:17 UTC, Zalmwel approved these changes, later dismissed

2020-11-22 13:22 UTC, closed without merging

2020-11-22 13:22 UTC, Steffb98 commented
byeee